Add GITEA_CUSTOM configuration in customization section
go-gitea/docs pull request #111
Opened 2017-04-06 18:36 UTC by blankoworld

Fix https://github.com/go-gitea/gitea/issues/1452 about missing GITEA_CUSTOM explanation in documentation

2017-04-06 20:33 UTC, strk requested changes
Please check the resolution of `custom/` dir

2017-04-06 20:33 UTC, strk commented on content/doc/advanced/customizing-gitea.en-us.md
> +**Note** that by default Gitea will use the `custom` folder in the current working directory.
I'm afraid at the moment it'll be the `custom` folder in the directory containing the `gitea` binary unless `GITEA_WORK_DIR` env is set, in which case that's the directory used to resolve relative paths like `custom/`

2017-04-07 10:15 UTC, blankoworld commented on content/doc/advanced/customizing-gitea.en-us.md
> +**Note** that by default Gitea will use the `custom` folder in the current working directory.
You're right, I didn't be aware that GITEA_WORK_DIR variable exists.
That's why it should be better to create a specific subsection in this page to explain how GITEA_WORK_DIR and GITEA_CUSTOM works.
Or, in another case: create a specific page to list all available environment variable for GITEA?
What's your opinion about that?

2017-04-07 11:38 UTC, strk commented
I think a section about environment variables will be great,
then you could reference those env variables at relevant places.

2017-04-08 07:40 UTC, strk commented on content/doc/advanced/customizing-gitea.en-us.md
> +**Note** that by default Gitea will use the `custom` folder in the current working directory.
Yes please add a section about env variables

2017-04-12 00:47 UTC, lunny commented
LGTM

2017-04-12 01:18 UTC, appleboy approved these changes

2017-04-12 01:18 UTC, appleboy commented
LGTM

2017-04-12 01:18 UTC, merged