Update customizing-gitea.en-us.md
go-gitea/docs pull request #114
Opened 2017-04-21 13:10 UTC by usef

Some changes to the update page.

2017-04-21 13:12 UTC, usef commented
Ok, this time I've done the pull request in the correct repository...

2017-04-21 14:41 UTC, strk requested changes
Looks good to me, except for the "install from binary" observation

2017-04-21 14:41 UTC, strk commented on content/doc/advanced/customizing-gitea.en-us.md
> +
Which binary contains the `custom` folder ? Last time I checked he official binary downloads were a single executable file...

2017-04-21 18:12 UTC, usef commented
committed the fixes.
the sense should now be more clear

2017-04-21 19:38 UTC, strk reviewed
Should you mention somewher ethat the `custom` folder can be configured to be elsewhere via an environment variable ?

2017-04-21 20:02 UTC, usef commented
Can you give me an entry point to read something about that? Should be nice to add a short reference about this feature.


Il 21 aprile 2017 21:38:23 CEST, Sandro Santilli <notifications@github.com> ha scritto:
>strk commented on this pull request.
>
>Should you mention somewher ethat the `custom` folder can be configured
>to be elsewhere via an environment variable ?
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/go-gitea/docs/pull/114#pullrequestreview-34107283

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

2017-04-21 20:18 UTC, strk commented
See #111 (which suggests the info should already be in the file)

2017-04-21 21:48 UTC, usef commented
done

2017-04-22 07:10 UTC, strk commented
LGTM, thanks

2017-06-01 12:41 UTC, andreynering commented
LGTM, sorry for the delay

2017-06-01 12:41 UTC, merged