Build caddy with plugins via multi-stage
go-gitea/docs pull request #121
Opened 2017-06-05 16:45 UTC by sapk

same as go-gitea/website#43 +  go-gitea/website#45

This will need a new drone sig (cc @lunny @appleboy and any who can sing ^^)

Fix #120

2017-06-06 01:18 UTC, appleboy approved these changes

2017-06-06 01:18 UTC, appleboy commented
LGTM

2017-06-07 10:15 UTC, Bwko commented
LGTM

2017-06-08 02:18 UTC, lunny commented
Have we changed drone to 0.6 now?

2017-06-08 02:20 UTC, appleboy commented
@lunny No. still needs to update drone sig file.

2017-06-08 12:00 UTC, bkcsoft commented
Does this work with the docker-version we have on demo? (v1.13.1 API 1.26)

2017-06-08 12:01 UTC, bkcsoft requested changes

2017-06-08 12:01 UTC, bkcsoft commented on Dockerfile
>  FROM alpine:edge
Does docker v1.13.1 have support for multi-image?

2017-06-08 12:01 UTC, bkcsoft commented on Dockerfile
>  FROM alpine:edge
(anyone can dismiss this review if this does work...)

2017-06-08 12:59 UTC, sapk commented on Dockerfile
>  FROM alpine:edge
We only need Docker > 17.05 for building but the resulting image is compatible with any old version (only the last image is kept). This function permit to use a builder pattern in one Dockerfile (with possible multi-builder).

2017-06-08 13:00 UTC, sapk commented on Dockerfile
>  FROM alpine:edge
For confirmation, this is already in production on https://gitea.io with the same solution.

2017-06-09 22:04 UTC, bkcsoft commented on Dockerfile
>  FROM alpine:edge
Well, it seems to bulid do :)

2017-06-09 22:04 UTC, bkcsoft approved these changes

2017-06-09 22:05 UTC, merged