Run as service in Ubuntu 16.04 via supervisor
go-gitea/docs pull request #142
Opened 2017-07-20 15:55 UTC by mmarif4u

As title.

2017-07-21 01:18 UTC, lunny commented
LGTM

2017-07-21 01:31 UTC, appleboy requested changes

2017-07-21 01:31 UTC, appleboy commented on content/doc/installation/run-as-service-in-ubuntu.en-us.md
> +#### Using supervisor
Please add an empty line between every section. It is hard to read this file.

2017-07-21 01:47 UTC, appleboy commented on content/doc/installation/run-as-service-in-ubuntu.en-us.md
> +And append the following code at the end of the file:
maybe add reference link: https://github.com/go-gitea/gitea/blob/master/contrib/supervisor/gitea

2017-07-21 15:01 UTC, mmarif4u commented
Updated with the requested changes.

2017-07-21 15:05 UTC, appleboy approved these changes

2017-07-21 15:06 UTC, appleboy commented
LGTM

2017-07-21 15:06 UTC, appleboy commented
make L-GTM work

2017-07-21 15:42 UTC, lafriks commented
I think this file need something like this at the begining of file
```
---
date: "2017-07-21T12:00:00+02:00"
title: "Run as service in Linux"
slug: "linux-service"
weight: 10
toc: true
draft: false
menu:
  sidebar:
    parent: "installation"
    name: "Linux service"
    weight: 20
    identifier: "linux-service"
---
```

2017-07-21 15:43 UTC, lafriks requested changes
See my comment about needed changes

2017-07-21 16:53 UTC, mmarif4u commented
@lafriks updated with the requested changes.

2017-07-21 18:00 UTC, lafriks approved these changes

2017-08-08 09:49 UTC, bkcsoft reviewed
Otherwise LGTM

2017-08-08 09:49 UTC, bkcsoft commented on content/doc/installation/run-as-service-in-ubuntu.en-us.md
> +#### Using supervisor
I think you need a newline before this row

2017-08-09 14:06 UTC, mmarif4u commented on content/doc/installation/run-as-service-in-ubuntu.en-us.md
> +#### Using supervisor
Do you mean adding new line after Run as service line?.

2017-08-09 19:05 UTC, lafriks commented on content/doc/installation/run-as-service-in-ubuntu.en-us.md
> +#### Using supervisor
@mmarif4u yes

2017-08-10 23:07 UTC, mmarif4u commented
Done.

2017-08-11 00:29 UTC, merged