added the ldap authentication.
go-gitea/docs pull request #144
Opened 2017-08-10 03:27 UTC by jlozadad

Please check the following:

1. Make sure you are targeting the `master` branch, pull requests on release branches are only allowed for bug fixes.
2. Read contributing guidelines: https://github.com/go-gitea/docs/blob/master/CONTRIBUTING.md
3. Describe what your pull request does and which issue you're targeting (if any)

**You MUST delete the content above including this line before posting, otherwise your pull request will be invalid.**

2017-08-10 07:42 UTC, lunny commented on content/doc/features/authentication.en-us.md
> +- In order to login to the Gogs using FreeIPA credentials, you need to create a bind account for Gogs to use:
Gogs should be Gitea.

2017-08-10 07:43 UTC, lunny commented
We also support OAuth(google+, github, twitter and about 20+ services) and OpenID login, if you can add them, that's be better. Of course, currently is also OK except some word `Gogs` should be replaced by `Gitea`.

2017-08-10 14:45 UTC, jlozadad commented on content/doc/features/authentication.en-us.md
> +- In order to login to the Gogs using FreeIPA credentials, you need to create a bind account for Gogs to use:
changing the doc part to Gitea but, are the config files in this doc still point to gogs or should be changed to gitea too?

2017-08-10 16:32 UTC, lafriks commented
Please also add LDAP sample for Microsoft AD:

Port: `389`
User search base: `(&(objectCategory=Person)(memberOf=CN=user-group,OU=example,DC=example,DC=org)(sAMAccountName=%s)(!(UserAccountControl:1.2.840.113556.1.4.803:=2)))`
Admin filter: `(memberOf=CN=admin-group,OU=example,DC=example,DC=org)`
Username: `sAMAccountName`

2017-08-10 18:47 UTC, lafriks requested changes

2017-08-10 18:47 UTC, lafriks commented on content/doc/features/authentication.en-us.md
> +## Microsoft AD
I was thinking that these need to be added under LDAP section as additional example lines for appropriate fields

2017-08-10 20:46 UTC, jlozadad commented on content/doc/features/authentication.en-us.md
> +## Microsoft AD
oops sorry for that. Let me change it.

2017-08-10 20:56 UTC, jlozadad commented
I can update for the other authentication we support but, I don't have docs for those.

2017-08-11 00:28 UTC, lunny commented
@jlozadad OK. that should be another PR.

2017-08-11 00:28 UTC, lunny commented
LGTM

2017-08-11 13:45 UTC, strk commented
There are references to "Gogs" still, in its current version, can you update them ?
Also, it would be great to describe what `Verify group membership in LDAP` does, exactly.

2017-08-11 17:55 UTC, jlozadad commented
looks like my previous comment got buried with the commit. But, yes I was asking the same thing. Some config still shows "gogs" and I was wondering if that part changed in gitea too or still the same. If all of it changed to gitea then plz confirm and I'll hange it again.

2017-08-19 19:53 UTC, lafriks commented
@jlozadad I was thinking that these examples needs to be added not in separate section but at the end of each description as additional example.
For example:
```
- User Search Base **(required)**
  - The LDAP base at which user accounts will be searched for.
  - Example: `ou=Users,dc=mydomain,dc=com`
  - Example for Microsoft AD: `(&(objectCategory=Person)(memberOf=CN=user-group,OU=example,DC=example,DC=org)(sAMAccountName=%s)(!(UserAccountControl:1.2.840.113556.1.4.803:=2)))`
```
etc

2017-08-23 18:19 UTC, jlozadad commented
so basically copy the example you mentioned and add it to the others? I'm not sure what would look different for the others.

2017-08-24 12:26 UTC, lafriks commented
@jlozadad yes add examples for Microsoft AD to sections port, user search base, admin filter and username

2017-08-24 16:21 UTC, jlozadad commented
I added the changes. Let me know if its correct.

2017-08-24 18:14 UTC, lafriks commented
Not really, I did mean only parts that are meant for each section like I did give example in comment 5 days ago

2017-09-28 05:44 UTC, appleboy commented
any updates on this?

2017-10-16 15:46 UTC, lafriks approved these changes

2017-10-16 15:47 UTC, lafriks commented
Fixed

2017-10-17 06:40 UTC, daviian commented
LGTM

2017-10-17 06:43 UTC, merged