add webhooks documentation
go-gitea/docs pull request #155
Opened 2017-09-27 15:48 UTC by UziTech

This is copied and changed from Gogs webhooks documentation

https://gogs.io/docs/features/webhook

2017-09-27 16:29 UTC, lafriks requested changes

2017-09-27 16:29 UTC, lafriks commented on content/doc/features/webhooks.en-us.md
> +X-Gogs-Event: push
Please add here also:
```
X-Gitea-Delivery: f6266f16-1bf3-46a5-9ea4-602e06ead473
X-Gitea-Event: push
```

2017-09-27 18:42 UTC, UziTech commented on content/doc/features/webhooks.en-us.md
> +X-Gogs-Event: push
done

2017-09-28 05:01 UTC, lafriks approved these changes

2017-09-28 05:03 UTC, lafriks commented
LGTM

2017-09-28 05:43 UTC, appleboy approved these changes

2017-09-28 05:43 UTC, appleboy commented
LGTM

2017-09-28 05:43 UTC, merged