Update from-gogs.en-us.md
go-gitea/docs pull request #42
Opened 2016-12-28 16:59 UTC by termlimit

Updated upgrade from gogs instructions. This is for binary, however should work for others as well.

2016-12-29 09:18 UTC, tboerger requested changes
I have added various comments, the same comments apply to the master branch.

2016-12-29 09:18 UTC, tboerger commented on content/doc/upgrade/from-gogs.en-us.md
> +* wget https://github.com/go-gitea/gitea/archive/v1.0.0.zip
Please use https://dl.gitea.io as source

2016-12-29 09:18 UTC, tboerger commented on content/doc/upgrade/from-gogs.en-us.md
> +* If you have custom content migrated from gogs/custom/ folder, like templates or localization files, you should manually merge these because these files changed on Gitea.
The custom folder still applies for Gitea, just move `gogs/custom/conf` (not `gogs/custom/conf/app.ini`) to `gitea/custom/options`, this is used to override gitignores, labels, licenses, locales or readmes.

2016-12-29 09:18 UTC, tboerger commented on content/doc/upgrade/from-gogs.en-us.md
> +* unzip v1.0.0.zip
Not required for the binary from https://dl.gitea.io

2016-12-29 09:18 UTC, tboerger commented on content/doc/upgrade/from-gogs.en-us.md
> +* cp -r gitea-v1.0.0/options gitea/options
Not required for the binary from https://dl.gitea.io

2016-12-29 09:18 UTC, tboerger commented on content/doc/upgrade/from-gogs.en-us.md
> +FROM:
This doesn't format well. Just provide 2 code blocks.

2016-12-29 09:18 UTC, tboerger commented on content/doc/upgrade/from-gogs.en-us.md
> +* ~/gitea/gitea web
Write this as a code block

2016-12-29 09:18 UTC, tboerger commented on content/doc/upgrade/from-gogs.en-us.md
> +Update the gitea-v1.0.0/scripts file for your specific distro and environment then copy.
Just refer to https://github.com/go-gitea/gitea/tree/master/scripts because these files are not part of the file on https://dl.gitea.io.

2017-01-08 07:29 UTC, termlimit commented
Made the changes requested by tboerger, apologies again for the lengthy delay.

2017-01-08 09:15 UTC, lunny commented
conflict

2017-01-09 19:44 UTC, bkcsoft commented
Depricated in favour of #61 ?

2017-01-10 00:36 UTC, termlimit commented
Why? 61 is the same thing with less detail from what I can see. Up to you
guys. Let me know.

On Jan 9, 2017 11:44 AM, "bkcsoft" <notifications@github.com> wrote:

> Depricated in favour of #61 <https://github.com/go-gitea/docs/pull/61> ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/go-gitea/docs/pull/42#issuecomment-271387267>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AEklXs5-HfHD_QvdufNvpCOpBwYIe1Dxks5rQo46gaJpZM4LXDQy>
> .
>

2017-01-10 00:57 UTC, lunny requested changes

2017-01-10 00:57 UTC, lunny commented on content/doc/upgrade/from-gogs.en-us.md
> +If you are running Gogs version 0.9.113 or older, you can upgrade Gogs to Gitea smoothly. There are some steps to do below. Make sure to complete as the gitea user in ~:
I like use git user to complete it. I think We should say non-root user.

2017-01-10 00:57 UTC, lunny commented on content/doc/upgrade/from-gogs.en-us.md
> -* Copy `data/` folder from Gogs to Gitea. It contains issue attachments and avatars.
data directory is needed.

2017-01-10 04:33 UTC, termlimit commented on content/doc/upgrade/from-gogs.en-us.md
> -* Copy `data/` folder from Gogs to Gitea. It contains issue attachments and avatars.
lunny, I had `cp -r gogs gitea` that should copy the data/ folder from gogs to gitea. Do you want me to break that out as a separate line?

2017-01-10 04:34 UTC, termlimit commented on content/doc/upgrade/from-gogs.en-us.md
> +If you are running Gogs version 0.9.113 or older, you can upgrade Gogs to Gitea smoothly. There are some steps to do below. Make sure to complete as the gitea user in ~:
Sounds good, made the change to reflect non-root user, that is more logical

2017-01-10 04:36 UTC, termlimit commented on content/doc/upgrade/from-gogs.en-us.md
> +If you are running Gogs version 0.9.113 or older, you can upgrade Gogs to Gitea smoothly. There are some steps to do below. Make sure to complete as the gitea user in ~:
I added recommendation from pull request #57 as I tested this and upgraded without issue to Gitea v1.0.0. Consensus seems to be this is supported.

2017-01-10 11:09 UTC, lunny commented
seems conflict with #61

2017-01-11 04:56 UTC, termlimit commented
Looks like #61 has been merged, o well I will try again in the future. Thanks for helping guys!

2017-01-11 08:22 UTC, tboerger commented
https://github.com/go-gitea/docs/pull/61 have been merged to master, this PR targets the release/v1.0 branch. These branches should be properly in sync.

2017-01-13 04:09 UTC, termlimit commented
#68 was merged into v1.0 is this dead, should I close?

2017-01-13 07:33 UTC, lunny commented
Please close this one. @termlimit Thanks!

2017-01-13 09:22 UTC, termlimit commented
No problem on the close. Good call, between this being first contribution as well as my move and work. Just was unable to provide a resolution in a timely manner. I did learn a lot and I appreciate all the feedback.

2017-01-13 09:22 UTC, closed without merging