from-source: add info on how to install go-bindata
go-gitea/docs pull request #96
Opened 2017-02-24 23:25 UTC by silverwind

I've been mislead to installing `go-bindata` from a system repository which lead to failing builds, so I think it's best to include the right way to install it here.

2017-02-25 01:29 UTC, lunny requested changes

2017-02-25 01:29 UTC, lunny commented on content/doc/installation/from-source.en-us.md
> +If you want to build a `bindata` build, make sure to install the `go-bindata` dependency:
Maybe put this to line 61 is better.

2017-02-25 06:24 UTC, silverwind commented on content/doc/installation/from-source.en-us.md
> +If you want to build a `bindata` build, make sure to install the `go-bindata` dependency:
Thougt about it, but I think it fits better here in the Download section than in the Build section below.

2017-02-25 07:35 UTC, tboerger commented
:-1: this won't happen if you install and configure go properly. The bindata binary gets installed as a part of the generate make task. So don't tell the others that it's more complicated than now.

2017-02-25 08:35 UTC, silverwind commented
> The bindata binary gets installed as a part of the generate make task

It certainly didn't for me. I installed Go from Homebrew and `make generate` failed with `command not found: go-bindata`. I didn't add `$GOPATH/bin` to my PATH, but https://golang.org/doc/install doesn't recommend that, so it's a possibilty that the binary was installed there and was just not found.

2017-02-25 10:36 UTC, lunny commented
So in fact, @tboerger  make file should check if $GOPATH set, if not give a notice. Or even if `github.com/jteeuwen/go-bindata/...` you will also don't get `go-bindata` in your $PATH.

2017-02-25 11:26 UTC, tboerger commented
If go-bindata is not in the path it gets installed via go get

2017-02-25 12:18 UTC, lunny commented
`go get` don't means you have `go-bindata` command if you didn't set $GOPATH.

2017-02-25 12:21 UTC, andreynering commented
LGTM. I think it doesn't hurt to have this info.

2017-02-25 15:14 UTC, lunny commented
I mean if you didn't add your $GOPATH/bin to your $PATH, even if `go get`. It will also report cannot find go-bindata. I have also encounter this problem.

2017-02-25 16:28 UTC, tboerger commented
We clearly say within the guide that the golang setup is out of the scope of the docs. Setting the correct path is part of the go setup. Than you can directly document and maintain the entire go setup process.

2017-02-25 16:51 UTC, tboerger commented
If you want to do something useful mention to add the gopath bin folder to the path, otherwise not all requires commands will work

2017-02-26 11:52 UTC, silverwind commented
I just checked again: `make generate` *does* install `go-bindata`, but it prints `which: no go-bindata in` during the process because stderr is not redirected. I'll create a PR that fixes this, making this PR obsolete.

2017-02-26 11:52 UTC, closed without merging

2017-02-26 12:38 UTC, tboerger commented
Thanks!